spring.application.name=wallet
spring.datasource.url=jdbc:postgresql://localhost:5432/walletdb
spring.datasource.username=postgres
spring.datasource.password=123
jwt.secret=very-long-secret-key-1234
jwt.expiration=900000