spring.application.name=wallet
spring.datasource.url=jdbc:postgresql://localhost:5432/walletdb
spring.datasource.username=postgres
spring.datasource.password=123
jwt.secret=abcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblahabcxyz1234blahblah
jwt.expiration=900000